name: Lint Python Code

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyse code
        run: |
          files=$(find . -name "*.py")
          if [ -n "$files" ]; then
            for file in $files; do
              pylint "$file" --rcfile=.pylintrc --fail-under=7.0
            done
          else
            echo "No Python files found to lint."
          fi
